{{- range $index, $secondary := .Values.app.domains.secondary }}
apiVersion: sme.sap.com/v1alpha1
kind: ClusterDomain
metadata:
  name: {{ $secondary.clusterDomainName }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  dnsMode: Subdomain
  domain: {{ $secondary.domainHost }}
  ingressSelector:
  {{- range $k, $v := $.Values.app.istioIngressGatewayLabels }}
    {{ $k }}: {{ $v | default "invalidValue"}}
  {{- end }}
  tlsMode: Simple
{{- end }}
