{{- range $serviceName, $serviceSpec := .Values.serviceInstances }}
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: {{ $serviceSpec.name }}
spec:
  serviceOfferingName: {{ $serviceSpec.serviceOfferingName }}
  servicePlanName: {{ $serviceSpec.servicePlanName}}

  {{- if $serviceSpec.dataCenter }}
  dataCenter: {{ $serviceSpec.dataCenter }}
  {{- end }}

  {{- if $serviceSpec.servicePlanID }}
  servicePlanID: {{ $serviceSpec.servicePlanID }}
  {{- end }}

  {{- if $serviceSpec.externalName }}
  externalName: {{ $serviceSpec.externalName }}
  {{- end }}

  {{- if $serviceSpec.shared }}
  shared: {{ $serviceSpec.shared }}
  {{- end }}

  {{- if $serviceSpec.customTags }}
  customTags: {{ $serviceSpec.customTags | toYaml | nindent 4 }}
  {{- end }}

  {{- if $serviceSpec.userInfo }}
  userInfo: {{ $serviceSpec.userInfo | toYaml | nindent 4 }}
  {{- end }}

  {{- if $serviceSpec.btpAccessCredentialsSecret }}
  btpAccessCredentialsSecret: {{ $serviceSpec.btpAccessCredentialsSecret }}
  {{- end }}

  {{- if or $serviceSpec.parameters $serviceSpec.jsonParameters }}
  {{- $parameters := $serviceSpec.parameters | default (dict) }}
  {{- if and (eq $serviceSpec.serviceOfferingName "xsuaa") (or (not (get (get $parameters "oauth2-configuration") "redirect-uris")) (eq (len (get (get $parameters "oauth2-configuration") "redirect-uris")) 0)) }}
    {{- $redirectUris := include "redirectUris" $ | fromJson }}
    {{- $oauth2Cfg := merge ($redirectUris) (get $parameters "oauth2-configuration" | default dict) }}
    {{- $_ := set $parameters "oauth2-configuration" $oauth2Cfg }}
  {{- end }}
  {{- $jsonParameters := $serviceSpec.jsonParameters | default "{}" }}
  parameters: {{- $jsonParameters | fromJson | merge $parameters | toYaml | nindent 4 }}
  {{- end }}

  {{- if $serviceSpec.parametersFrom }}
  parametersFrom: {{ tpl ($serviceSpec.parametersFrom | toYaml) $ | nindent 4}}
  {{- end }}
{{- end }}
