---
apiVersion: sme.sap.com/v1alpha1
kind: CAPApplication
metadata:
  name: {{ include "appName" $ }}
spec:
  domainRefs:
  - kind: Domain
    name: {{ include "domainName" $ }}
  {{- range .Values.app.domains.additionalDomainRefs }}
  - kind: {{ .kind }}
    name: {{ .name }}
  {{- end }}
  btpAppName: {{ include "appName" $ }}
  globalAccountId: {{.Values.btp.globalAccountId}}
  btp:
    services:
    {{- $serviceInstances := .Values.serviceInstances }}
    {{- range $k, $v := .Values.serviceBindings }}
    {{- $serviceInstance := dict }}
    {{- range $sik, $siv := $serviceInstances }}
      {{- if eq $siv.name $v.serviceInstanceName }}
        {{- $serviceInstance = $siv }}
      {{- end }}
    {{- end }}
    {{- if hasKey $serviceInstance "serviceOfferingName" }}
    - class: {{ get $serviceInstance "serviceOfferingName" | default "invalidValue" }}
      {{- if $v.externalName }}
      name: {{ $v.externalName | default "invalidValue" }}
      {{- else }}
      name: {{ $v.name | default "invalidValue" }}
      {{- end }}
      secret: {{ $v.secretName | default "invalidValue" }}
    {{- end }}
    {{- end }}
---
apiVersion: sme.sap.com/v1alpha1
kind: CAPApplicationVersion
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/resource-policy: keep
  name: {{ include "capApplicationVersionName" $ }}
spec:
  capApplicationInstance: {{ include "appName" $ }}
  version: "{{ .Release.Revision }}"
  registrySecrets:
    {{- range .Values.imagePullSecrets }}
    - {{.}}
    {{- end }}
  workloads:
  - name: server
    labels:
      sme.sap.com/app-type: {{ include "appName" $ }}
    consumedBTPServices:
    - {{ include "originalAppName" $ }}-uaa-bind
    - {{ include "originalAppName" $ }}-saas-registry-bind
    - {{ include "originalAppName" $ }}-service-manager-bind
    deploymentDefinition:
      type: service
      image: {{ .Values.workloads.server.image }}
      {{- if .Values.hanaInstanceId }}
      env:
      - name: CDS_CONFIG
        value: '{"requires":{"cds.xt.DeploymentService":{"hdi": { "create": {"database_id": "{{.Values.hanaInstanceId}}"}}}}}'
      {{- end }}
      ports:
      - name: server-port
        port: 4004
        appProtocol: http
  - name: content-deploy
    labels:
      sme.sap.com/app-type: {{ include "appName" $ }}
    consumedBTPServices:
    - {{ include "originalAppName" $ }}-uaa-bind
    - {{ include "originalAppName" $ }}-saas-registry-bind
    {{- if eq (include "hasService" (dict "si" .Values.serviceInstances "offeringName" "html5-apps-repo" "planName" "app-host")) "true" }}
    - {{ include "originalAppName" $ }}-html5-repo-host-bind
    {{- end }}
    {{- if eq (include "hasService" (dict "si" .Values.serviceInstances "offeringName" "content-agent" "planName" "application")) "true" }}
    - {{ include "originalAppName" $ }}-content-agent-bind
    {{- end }}
    jobDefinition:
      type: Content
      image: {{ .Values.workloads.contentDeploy.image }}
  serviceExposures:
  - subDomain: {{ include "originalAppName" $ }}
    routes:
    - workloadName: server
      port: 4004
