name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [lts/*, lts/-1]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g @sap/cds-dk
    - run: npm i
    - run: cds v
    - run: npm run test

  analysis:
    name: Analyze with Sonar Cloud
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code for Sonar Analysis
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: run coverage tests
      run: |
        npm i -g @sap/cds-dk
        npm i
        npm run test-coverage-lcov
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
